spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: root
    password: kw0810

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
          kakao:
            client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:your-kakao-client-secret}

ai:
  server:
    uri: "http://localhost:8000"

logging:
  level:
    root: INFO
    com.boterview: DEBUG
    org.mybatis: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
