

spring:
  application:
    name: interview-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile_nickname, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  type-aliases-package: com.boterview.interview_api.domain

init:
  admin:
    email: ${INIT_ADMIN_EMAIL:admin@boterview.com}
    password: ${INIT_ADMIN_PASSWORD:admin1234}
  user:
    email: ${INIT_USER_EMAIL:user@boterview.com}
    password: ${INIT_USER_PASSWORD:user1234}

jwt:
  access-token:
    secret: ${JWT_ACCESS_SECRET:boterview-access-secret-key-must-be-at-least-32-characters-long}
    expiration-ms: ${JWT_ACCESS_EXPIRATION:1800000}
  refresh-token:
    secret: ${JWT_REFRESH_SECRET:boterview-refresh-secret-key-must-be-at-least-32-characters-long}
    expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}
  max-active: ${JWT_MAX_ACTIVE:1}
